---
- hosts: localhost
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Install desired packages
        apt: "name={{ item }} state=present update_cache=true cache_valid_time=600"
        with_items:
            - iftop
            - tree
            - wget

      - name: Install Docker keys
        apt_key: state=present keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9
      - name: Install Docker repository
        apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present
      - name: Install Docker
        apt: name=lxc-docker state=latest update_cache=true cache_valid_time=600
      - name: Add ubuntu to the docker group
        user: name=ubuntu state=present groups=docker
      - name: Expose the daemon over insecure HTTP
        lineinfile: dest=/etc/default/docker line='DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"'
      - name: Set Memory and Swap Accounting
        lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""' line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
      - name: Rebuild GRUB
        command: update-grub

      # install NewRelic monitoring agent
      - apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present
      - apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present
      - apt: name=newrelic-sysmond state=present update_cache=yes
      - command: nrsysmond-config --set license_key=9a3465dc990aa65ee1037041a7d0f770ef428cfd 
      - service: name=newrelic-sysmond state=restarted
